=== mPunc/Album_adder_project/album-adder-react/public/data/albumi_data_validation.dtd
<!ELEMENT albumi_data (albumi*)>
<!ELEMENT albumi (album+)>
<!ATTLIST albumi razdoblje CDATA #REQUIRED>
<!ELEMENT album (id, naslov, umjetnik, zanr, godina, producenti, slika_link)>
<!ELEMENT id (#PCDATA)>
<!ELEMENT naslov (#PCDATA)>
<!ELEMENT umjetnik (#PCDATA)>
<!ATTLIST umjetnik tip (solo | grupa) #REQUIRED>
<!ELEMENT zanr (#PCDATA)>
<!ELEMENT godina (#PCDATA)>
<!ELEMENT producenti (producent+)>
<!ELEMENT producent (#PCDATA)>
<!ELEMENT slika_link (#PCDATA)>

=== mPunc/Album_adder_project/album-adder-react/public/data/albumi_data.xml
<?xml version='1.0' encoding='utf-8'?>
<!DOCTYPE albumi_data SYSTEM "albumi_data_validation.dtd">
<albumi_data>
    <albumi razdoblje="80">
        <album>
            <id>0</id>
            <naslov>Thriller</naslov>
            <umjetnik tip="solo">Michael Jackson</umjetnik>
            <zanr>Pop</zanr>
            <godina>1982</godina>
            <producenti>
                <producent>Quincy Jones</producent>
            </producenti>
            <slika_link />
        </album>
        <album>
            <id>1</id>
            <naslov>Back in Black</naslov>
            <umjetnik tip="grupa">AC/DC</umjetnik>
            <zanr>Hard Rock</zanr>
            <godina>1980</godina>
            <producenti>
                <producent>Robert John "Mutt" Lange</producent>
            </producenti>
            <slika_link />
        </album>
        <album>
            <id>2</id>
            <naslov>The Joshua Tree</naslov>
            <umjetnik tip="grupa">U2</umjetnik>
            <zanr>Rock</zanr>
            <godina>1987</godina>
            <producenti>
                <producent>Brian Eno</producent>
                <producent>Daniel Lanois</producent>
            </producenti>
            <slika_link />
        </album>
        <album>
            <id>3</id>
            <naslov>Like a Virgin</naslov>
            <umjetnik tip="solo">Madonna</umjetnik>
            <zanr>Pop</zanr>
            <godina>1984</godina>
            <producenti>
                <producent>Nile Rodgers</producent>
            </producenti>
            <slika_link />
        </album>
        <album>
            <id>4</id>
            <naslov>Appetite for Destruction</naslov>
            <umjetnik tip="grupa">Guns N' Roses</umjetnik>
            <zanr>Hard Rock</zanr>
            <godina>1987</godina>
            <producenti>
                <producent>Mike Clink</producent>
            </producenti>
            <slika_link />
        </album>
        <album>
            <id>5</id>
            <naslov>Born in the U.S.A.</naslov>
            <umjetnik tip="solo">Bruce Springsteen</umjetnik>
            <zanr>Rock</zanr>
            <godina>1984</godina>
            <producenti>
                <producent>Bruce Springsteen</producent>
                <producent>Jon Landau</producent>
                <producent>Chuck Plotkin</producent>
                <producent>Steve Van Zandt</producent>
            </producenti>
            <slika_link />
        </album>
        <album>
            <id>6</id>
            <naslov>Hounds of Love</naslov>
            <umjetnik tip="solo">Kate Bush</umjetnik>
            <zanr>Art Pop</zanr>
            <godina>1985</godina>
            <producenti>
                <producent>Kate Bush</producent>
            </producenti>
            <slika_link />
        </album>
        <album>
            <id>7</id>
            <naslov>Sign o' the Times</naslov>
            <umjetnik tip="solo">Prince</umjetnik>
            <zanr>Funk, Rock, R&amp;B</zanr>
            <godina>1987</godina>
            <producenti>
                <producent>Prince</producent>
            </producenti>
            <slika_link />
        </album>
        <album>
            <id>8</id>
            <naslov>Disintegration</naslov>
            <umjetnik tip="grupa">The Cure</umjetnik>
            <zanr>Gothic Rock</zanr>
            <godina>1989</godina>
            <producenti>
                <producent>Robert Smith</producent>
                <producent>David M. Allen</producent>
            </producenti>
            <slika_link />
        </album>
        <album>
            <id>9</id>
            <naslov>Brothers in Arms</naslov>
            <umjetnik tip="grupa">Dire Straits</umjetnik>
            <zanr>Rock</zanr>
            <godina>1985</godina>
            <producenti>
                <producent>Mark Knopfler</producent>
                <producent>Neil Dorfsman</producent>
            </producenti>
            <slika_link />
        </album>
    </albumi>

    <albumi razdoblje="90">
        <album>
            <id>10</id>
            <naslov>Nevermind</naslov>
            <umjetnik tip="grupa">Nirvana</umjetnik>
            <zanr>Grunge</zanr>
            <godina>1991</godina>
            <producenti>
                <producent>Butch Vig</producent>
            </producenti>
            <slika_link />
        </album>
        <album>
            <id>11</id>
            <naslov>OK Computer</naslov>
            <umjetnik tip="grupa">Radiohead</umjetnik>
            <zanr>Alternative Rock</zanr>
            <godina>1997</godina>
            <producenti>
                <producent>Nigel Godrich</producent>
                <producent>Radiohead</producent>
            </producenti>
            <slika_link />
        </album>
        <album>
            <id>12</id>
            <naslov>Ten</naslov>
            <umjetnik tip="grupa">Pearl Jam</umjetnik>
            <zanr>Grunge</zanr>
            <godina>1991</godina>
            <producenti>
                <producent>Rick Parashar</producent>
                <producent>Pearl Jam</producent>
            </producenti>
            <slika_link />
        </album>
        <album>
            <id>13</id>
            <naslov>The Miseducation of Lauryn Hill</naslov>
            <umjetnik tip="solo">Lauryn Hill</umjetnik>
            <zanr>R&amp;B, Hip-Hop</zanr>
            <godina>1998</godina>
            <producenti>
                <producent>Lauryn Hill</producent>
                <producent>Che Pope</producent>
                <producent>Vada Nobles</producent>
            </producenti>
            <slika_link />
        </album>
        <album>
            <id>14</id>
            <naslov>Metallica (The Black Album)</naslov>
            <umjetnik tip="grupa">Metallica</umjetnik>
            <zanr>Heavy Metal</zanr>
            <godina>1991</godina>
            <producenti>
                <producent>Bob Rock</producent>
            </producenti>
            <slika_link />
        </album>
        <album>
            <id>15</id>
            <naslov>The Chronic</naslov>
            <umjetnik tip="solo">Dr. Dre</umjetnik>
            <zanr>Hip-Hop</zanr>
            <godina>1992</godina>
            <producenti>
                <producent>Dr. Dre</producent>
            </producenti>
            <slika_link />
        </album>
        <album>
            <id>16</id>
            <naslov>Jagged Little Pill</naslov>
            <umjetnik tip="solo">Alanis Morissette</umjetnik>
            <zanr>Alternative Rock</zanr>
            <godina>1995</godina>
            <producenti>
                <producent>Glen Ballard</producent>
            </producenti>
            <slika_link />
        </album>
        <album>
            <id>17</id>
            <naslov>Superunknown</naslov>
            <umjetnik tip="grupa">Soundgarden</umjetnik>
            <zanr>Grunge</zanr>
            <godina>1994</godina>
            <producenti>
                <producent>Michael Beinhorn</producent>
                <producent>Soundgarden</producent>
            </producenti>
            <slika_link />
        </album>
        <album>
            <id>18</id>
            <naslov>Ready to Die</naslov>
            <umjetnik tip="solo">The Notorious B.I.G.</umjetnik>
            <zanr>Hip-Hop</zanr>
            <godina>1994</godina>
            <producenti>
                <producent>Sean Combs</producent>
                <producent>Easy Mo Bee</producent>
                <producent>DJ Premier</producent>
            </producenti>
            <slika_link />
        </album>
        <album>
            <id>19</id>
            <naslov>Odelay</naslov>
            <umjetnik tip="solo">Beck</umjetnik>
            <zanr>Alternative Rock</zanr>
            <godina>1996</godina>
            <producenti>
                <producent>Beck</producent>
                <producent>The Dust Brothers</producent>
            </producenti>
            <slika_link />
        </album>
    </albumi>

    <albumi razdoblje="2000">
        <album>
            <id>20</id>
            <naslov>Kid A</naslov>
            <umjetnik tip="grupa">Radiohead</umjetnik>
            <zanr>Experimental Rock</zanr>
            <godina>2000</godina>
            <producenti>
                <producent>Nigel Godrich</producent>
                <producent>Radiohead</producent>
            </producenti>
            <slika_link />
        </album>
        <album>
            <id>21</id>
            <naslov>The Marshall Mathers LP</naslov>
            <umjetnik tip="solo">Eminem</umjetnik>
            <zanr>Hip-Hop</zanr>
            <godina>2000</godina>
            <producenti>
                <producent>Dr. Dre</producent>
                <producent>Mel-Man</producent>
            </producenti>
            <slika_link />
        </album>
        <album>
            <id>22</id>
            <naslov>Yankee Hotel Foxtrot</naslov>
            <umjetnik tip="grupa">Wilco</umjetnik>
            <zanr>Alternative Rock</zanr>
            <godina>2002</godina>
            <producenti>
                <producent>Wilco</producent>
                <producent>Jim O'Rourke</producent>
            </producenti>
            <slika_link />
        </album>
        <album>
            <id>23</id>
            <naslov>Is This It</naslov>
            <umjetnik tip="grupa">The Strokes</umjetnik>
            <zanr>Indie Rock</zanr>
            <godina>2001</godina>
            <producenti>
                <producent>Gordon Raphael</producent>
            </producenti>
            <slika_link />
        </album>
        <album>
            <id>24</id>
            <naslov>Speakerboxxx/The Love Below</naslov>
            <umjetnik tip="grupa">OutKast</umjetnik>
            <zanr>Hip-Hop, Funk</zanr>
            <godina>2003</godina>
            <producenti>
                <producent>Andr√© 3000</producent>
                <producent>Big Boi</producent>
            </producenti>
